#pragma config(StandardModel, "RVW Anemobot")
#pragma config(RenamedStdModelMotor, motorA, armMotor)
#pragma config(RenamedStdModelSensor, S3, colorSensor)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// End main
task main()
{
    // Move until stop button is pressed
	while(getButtonPress(buttonEnter) == 0)
	{
    // Set both wheels to move at same speed ie. go forward
		setMotorSpeed(leftMotor, 50); 
		setMotorSpeed(rightMotor, 50);

        // stop moving when 1cm black line is detected
		if (SensorValue(colorSensor) < 40)
		{
			setMotorSpeed(leftMotor, 0);
			setMotorSpeed(rightMotor, 0);
            
		} // end if statement
        
	} // end whie loop

} // end main
