#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     distanceSensor, sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

// 


// Main function
task main()
{
    // Variables
	int lightValue;  // variable to store light sensor value
	int darkValue;   // variable to store dark sensor value
	int sumValue;    // variable to store sum of light and dark values
	int thresholdValue;  // variable to store threshold value

	while(SensorValue[touchSensor] == 0)
	{
		displayCenteredBigTextLine(4, "touch for dark");  // display message to prompt for dark reading
		displayCenteredBigTextLine(2, "light val = %d",SensorValue[colorSensor]);  // display light sensor value
        
	} // End while

	lightValue = SensorValue[colorSensor];  // store light sensor value
	wait1Msec(1000);  // wait for 1 second

	while(SensorValue(touchSensor) == 0)
	{
		// displayCenteredBigTextLine(2, "touch for dark val");
		displayCenteredBigTextLine(4, "touch for summary");  // display message to prompt for summary
		displayCenteredBigTextLine(2, "dark val = %d",SensorValue[colorSensor]);  // display dark sensor value
	}

	darkValue = SensorValue[colorSensor];  // store dark sensor value
	sumValue = lightValue + darkValue;     // calculate sum of light and dark values
	thresholdValue = sumValue / 2;           // calculate threshold value
	displayCenteredBigTextLine(2, "dark = %d",darkValue);  // display dark value
	displayCenteredBigTextLine(4, "light = %d" ,lightValue);  // display light value
	displayCenteredBigTextLine(6, "threshold = %d",thresholdValue);  // display threshold value

	sleep(3000);  // pause for 3 seconds
    
} // End main
