#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*------------------------------------------------------------------------------------------------
  This program will move your robot make a series of moves for different lengths of time.
  At the end of the program, all motors will shut down automatically and turn off.

                            ROBOT CONFIGURATION: LEGO EV3 REM Bot
    MOTORS & SENSORS:
    [I/O Port]          [Name]              [Type]                [Description]
    MotorC        	leftMotor           LEGO EV3 Motor	  Left side motor
    MotorB       	rightMotor          LEGO EV3 Motor	  Right side motor (reversed)
------------------------------------------------------------------------------------------------*/

void randomDirection(void);
void moveRobot(long nMotorRatio, long time, long power);


// Function for turning based on the random number generated
void randomDirection(void)
{
    // Generate either 0 or 1
    int direction = random(1);

    if (direction == 1) // turn left if 1 is returned
    {
        moveRobot(-50, 3000, 50);
        moveRobot(0, 5000, 0); // pause for 5 seconds
    }
    else // turn right if 0 is returned
    {
        moveRobot(50, 3000, 50);
        moveRobot(0, 5000, 0); // pause for 5 seconds
    } // End if else
    
} // End function


// Function for driving the robot
void moveRobot(long nMotorRatio, long time, long power)
{

	setMotorSyncTime(leftMotor, rightMotor, nMotorRatio, time, power); // turn left at half power for 1 second
	sleep(time);

	/* setMotorSyncTime(leftMotor, rightMotor, 0, 1000, 50); // go straight at half power for 1 second
	sleep(1500);

	setMotorSyncTime(leftMotor, rightMotor, 100, 1000, 50); // turn right at half power for 1 second
	sleep(1500);

	setMotorSyncTime(leftMotor, rightMotor, 50, 1000, 50); // go left diagonal at half power for 1 second
	sleep(1500);

	setMotorSyncTime(leftMotor, rightMotor, -50, 1000, 50); // go right diagonal at half power for 1 second
	sleep(1500); */
    
} // End function


// Main function
task main()
{
    // Execute random number choice function
    randomDirection();

    // Test moveRobot function - go straight for 1 second at half power
	  moveRobot(0, 1000, 50);
    moveRobot(0, 5000, 0); // pause for 5 seconds

    // Go in a square and return to original position
    moveRobot(0, 3000, 50); // go forward at half speed for 2 seconds
    moveRobot(-100, 500, 50); // turn left at half speed in .5 seconds
    moveRobot(0, 3000, 50); // go forward at half speed for 2 seconds
    moveRobot(-100, 500, 50); // turn left at half speed in .5 seconds
    moveRobot(0, 3000, 50); // go forward at half speed for 2 seconds
    moveRobot(-100, 500, 50); // turn left at half speed in .5 seconds
    moveRobot(0, 3000, 50); // go forward at half speed for 2 seconds
    moveRobot(-100, 500, 50); // turn left at half speed in .5 seconds
    moveRobot(0, 5000, 0); // pause for 5 seconds

    /* Go forward for 2 seconds at full speed, then do 180 degree spin, and at half speed travel back
    to the original starting position. */
    moveRobot(0, 2000, 100); // go forward
    moveRobot(-50, 1000, 50); // do 180 degree spin
    moveRobot(0, 4000, 50); // travel back

} // End main
