#pragma config(Sensor, S2,     touchLeft,      sensorEV3_Touch)  // configure left touch sensor
#pragma config(Sensor, S3,     touchRight,     sensorEV3_Touch)  // configure right touch sensor
#pragma config(Sensor, S4,     ultraSonic,     sensorEV3_Ultrasonic)  // configure ultrasonic sensor
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)  // configure left motor
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)  // configure right motor
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

#define circumference 17.27  // constant for circumference of the wheel

// functions
void turn90(char direction, long power);  // function to turn 90 degrees
void reset();  // function to reset motor encoders
void driveUntilBump(long power);  // function to drive until bump is detected
void driveUntilWall(long power);  // function to drive until wall is detected
void drive(long nMotorRatio, long dist, long power);  // function to drive a distance


task main()  // main task
{
	driveUntilBump(75);  // drive until bump is detected

	turn90('l', 50);  // turn left 90 degrees

	driveUntilWall(75);  // drive until wall is detected

	turn90('l', 50);  // turn left 90 degrees

	driveUntilWall(75);  // drive until wall is detected

	turn90('l', 50);  // turn left 90 degrees

	drive(0, 30, 50);  // drive forward 30 units at power 50
    
} // End main


// reset motor encoders
void reset()
{
	resetMotorEncoder(leftMotor);  // reset left motor encoder
	resetMotorEncoder(rightMotor);  // reset right motor encoder
    
} // End function

// drive until detects bump, then reverse
void driveUntilBump(long power)
{
	while(!SensorValue(touchLeft) && !SensorValue(touchRight))  // loop until either touch sensor is pressed
	{
		setMotorSync(leftMotor, rightMotor, 0, power);  // drive forward
	}

	setMotorSync(leftMotor, rightMotor, 0, -50);  // reverse
	sleep(500);  // wait for a short moment
    
} // End function


// turn 90 degrees in specified direction
void turn90(char direction, long power)
{
	reset();  // reset encoders

	// check direction for rotation
	if (direction == 'l'  || direction == 'L')  // if left turn
	{
		// turn left 180 degrees
		setMotorSyncEncoder(leftMotor, rightMotor, 100, 180, power);
		waitUntilMotorStop(leftMotor);
	}
	else if (direction == 'r'  || direction == 'R')  // if right turn
	{
		// turn right 180 degrees
		setMotorSyncEncoder(leftMotor, rightMotor, -100, 180, power);
		waitUntilMotorStop(leftMotor);
	}
    
} // End function


// Drive until a wall is sensed at set power
void driveUntilWall(long power)
{
	while(getUSDistance(ultraSonic) > 10)  // loop until distance to wall is less than 10 units
	{
		setMotorSync(leftMotor, rightMotor, 0, power);  // drive forward
	}
    
} // End function


// Drive a distance at a ratio, to a set power level
void drive(long nMotorRatio, long dist, long power)
{
	float rotations = 360 * (dist / circumfrance);  // calculate rotations based on distance

	reset();  // reset encoders

	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, rotations, power);  // set motors to drive specific distance at specified power
	waitUntilMotorStop(leftMotor);  // wait until left motor stops
    
} // End function
