#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard!!*//

#define circumference 17.27  // circumference of the wheel

// Functions
void drive(long nMotorRatio, long dist, long power);  // drive function
void turn90(char direction, long power);  // function to turn 90 degrees
void square(int perimeter);  // function to make a square
void returnSlow(int distance);  // function to return slowly
void reset();  // function to reset motor encoders


task main()  // main task
{
	// perform square with perimeter of 240cm
	square(240);

	// drive 100cm and return slowly
	returnSlow(100);
    
} // End main

// reset motor encoders
void reset()
{
	resetMotorEncoder(leftMotor);  // reset left motor encoder
	resetMotorEncoder(rightMotor);  // reset right motor encoder
    
} // End function


// drive function
void drive(long nMotorRatio, long dist, long power)
{
	float rotations = 360 * (dist / circumfrance);  // calculate rotations based on distance

	reset();  // reset encoders

	setMotorSyncEncoder(leftMotor, rightMotor, nMotorRatio, rotations, power);  // set motors to drive specific distance at specified power
    waitUntilMotorStop(leftMotor);  // wait until left motor stops
    
} // End function


// function to turn 90 degrees
void turn90(char direction, long power)
{
	reset();  // reset encoders

	// determine direction for rotation
	if (direction == 'l'  || direction == 'L')  // if left turn
	{
		// turn left 180 degrees
		setMotorSyncEncoder(leftMotor, rightMotor, 100, 180, power);
		waitUntilMotorStop(leftMotor);
	}
	else if (direction == 'r'  || direction == 'R')  // if right turn
	{
		// turn right 180 degrees
		setMotorSyncEncoder(leftMotor, rightMotor, -100, 180, power);
		waitUntilMotorStop(leftMotor);
	} // End if else
    
} // End function


// function to make a square
void square(int perimeter)
{
	int sideLength = perimeter / 4;  // calculate length of each side
	int randInt = random(1);  // generate random number
	char direction;

	if (randInt == 0)  // if random number is 0
	{
		direction = 'l';  // set direction to left
	}
	else
	{
		direction = 'r';  // set direction to right
	} // End if else

	// logic for moving in a square
	for(int i = 0; i < 4; i++)
	{
		drive(0, sideLength, 50);  // drive forward
		sleep(200);  // pause for a moment
		turn90(direction, 50);  // turn 90 degrees
	} // End for
    
} // End function


// function to return slowly
void returnSlow(int distance)
{
	drive(0, distance, 100);  // drive forward
	sleep(200);  // pause for a moment

	turn90('r', 50);  // turn right 90 degrees
	turn90('r', 50);  // turn right 90 degrees

	sleep(200);  // pause for a moment

	drive(0, distance, 25);  // drive forward slowly
    
} // End function
