#pragma config(Sensor, S4,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Motor,  motorA,  gyroMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,  leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,  rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Task function to enable Gyro driving
task gyroDrive();


// Main task function
task main()
{
    // Start gyroDrive task
    startTask(gyroDrive);

    // Run until the middle button gets pressed
    while(getButtonPress(buttonEnter) == 0)
    {
        // Request the user to press the middle button to end program
        displayBigTextLine(5, "Press enter to end");

        // Set motor speed to half of Gyro degrees
        setMotorSync(leftMotor, rightMotor, 0, (getGyroDegrees(gyroSensor) / 2));
        
    } // End while

    // End tasks when program is finished
    stopAllTasks();
    
} // End main function

// Turn the gyro 90 degrees (from -45 degrees to +45 degrees)
task gyroDrive()
{
    // Loop until no longer true
    while(true)
    {
        // Reset motor and move 90 degrees at speed 5
        resetMotorEncoder(gyroMotor);
        setMotorTarget(gyroMotor, 90, 5);
        waitUntilMotorStop(gyroMotor);

        // Stop for 0.1 seconds
        sleep(100);

        // Reset motor and move -90 degrees at speed 5
        resetMotorEncoder(gyroMotor);
        setMotorTarget(gyroMotor, -90, 5);
        waitUntilMotorStop(gyroMotor);
        
        // Reset Gyro Sensor to 0
        resetGyro(gyroSensor);
        
    } // End while
    
} // End task function
